// Generated by bin/generate-shipped.py from schemas/. Do not edit.

package wrench

// shippedSchema is one schema as it sits in schemas/, carried as source so
// the pack links a single static binary and needs no file at run time.
type shippedSchema struct {
	Name string
	Text string
}

// shippedSchemas is the whole directory, in filename order.
var shippedSchemas = []shippedSchema{
	{
		"definitions.schema.json",
		"{\n" +
			"  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n" +
			"  \"$id\": \"https://scriptedworld.github.io/wrench/definitions.schema.json\",\n" +
			"  \"title\": \"definitions\",\n" +
			"  \"description\": \"Values a runner substitutes for a jig's placeholders. One level of names and scalar val" +
			"ues, the same shape whether it is a jig's own block or a file supplying them, so there is one thing to valid" +
			"ate and one thing to read.\",\n" +
			"\n" +
			"  \"type\": \"object\",\n" +
			"\n" +
			"  \"propertyNames\": {\n" +
			"    \"pattern\": \"^[a-z][a-z0-9_]*$\",\n" +
			"    \"description\": \"A placeholder's name, matching what {name} spells in a command. Underscored, because " +
			"template variables are underscored where command-line flags are hyphenated.\"\n" +
			"  },\n" +
			"\n" +
			"  \"additionalProperties\": {\n" +
			"    \"type\": [\"string\", \"number\", \"boolean\"],\n" +
			"    \"description\": \"A literal. It carries no substitutions of its own, so reading the file settles it and" +
			" nothing resolves in terms of anything else. Scalar because a list has no defined spelling on a command line" +
			". An empty string is a value; the absence of the key is not.\"\n" +
			"  }\n" +
			"}\n",
	},
	{
		"envelope.schema.json",
		"{\n" +
			"  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n" +
			"  \"$id\": \"https://scriptedworld.github.io/wrench/envelope.schema.json\",\n" +
			"  \"title\": \"envelope\",\n" +
			"  \"description\": \"A result envelope. Every producer in the ecosystem writes one of these, and every consu" +
			"mer reads it the same way. success is the only key every envelope carries; the rest is open so whatever deta" +
			"il a producer holds can travel with the result.\",\n" +
			"\n" +
			"  \"type\": \"object\",\n" +
			"  \"required\": [\"success\"],\n" +
			"\n" +
			"  \"properties\": {\n" +
			"    \"version\": {\n" +
			"      \"type\": \"string\",\n" +
			"      \"pattern\": \"^(0|[1-9]\\\\d*)\\\\.(0|[1-9]\\\\d*)\\\\.(0|[1-9]\\\\d*)(?:-((?:0|[1-9]\\\\d*|\\\\d*[a-" +
			"zA-Z-][0-9a-zA-Z-]*)(?:\\\\.(?:0|[1-9]\\\\d*|\\\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\\+([0-9a-zA-Z-]+(?:\\\\" +
			".[0-9a-zA-Z-]+)*))?$\",\n" +
			"      \"description\": \"The version of this format the document claims to conform to, as semver. Optional, " +
			"and absent means the document claims nothing, which is every document written before this field existed. Pre" +
			"sent, it lets a consumer refuse a major it does not understand rather than failing later on a field it canno" +
			"t find.\"\n" +
			"    },\n" +
			"\n" +
			"    \"success\": {\n" +
			"      \"type\": \"boolean\",\n" +
			"      \"description\": \"Whether what this envelope describes passed. The authoritative verdict.\"\n" +
			"    },\n" +
			"\n" +
			"    \"reasons\": {\n" +
			"      \"type\": \"array\",\n" +
			"      \"description\": \"Why. Present when success is false. A member's shape is open beyond the two keys ev" +
			"ery consumer can count on.\",\n" +
			"      \"items\": { \"$ref\": \"#/$defs/reason\" }\n" +
			"    },\n" +
			"\n" +
			"    \"metadata\": {\n" +
			"      \"type\": \"object\",\n" +
			"      \"description\": \"Optional. Carries statistics and evidence where a producer has them.\",\n" +
			"      \"properties\": {\n" +
			"        \"statistics\": {\n" +
			"          \"description\": \"Whatever the producer counted.\"\n" +
			"        },\n" +
			"        \"evidence\": {\n" +
			"          \"description\": \"What the result rests on, by path.\"\n" +
			"        }\n" +
			"      }\n" +
			"    }\n" +
			"  },\n" +
			"\n" +
			"  \"if\": {\n" +
			"    \"properties\": { \"success\": { \"const\": false } },\n" +
			"    \"required\": [\"success\"]\n" +
			"  },\n" +
			"  \"then\": {\n" +
			"    \"required\": [\"reasons\"],\n" +
			"    \"properties\": {\n" +
			"      \"reasons\": { \"minItems\": 1 }\n" +
			"    }\n" +
			"  },\n" +
			"\n" +
			"  \"$defs\": {\n" +
			"    \"reason\": {\n" +
			"      \"type\": \"object\",\n" +
			"      \"required\": [\"message\", \"kind\"],\n" +
			"      \"properties\": {\n" +
			"        \"message\": {\n" +
			"          \"type\": \"string\",\n" +
			"          \"description\": \"Renderable by any consumer, which is what makes it required.\"\n" +
			"        },\n" +
			"        \"kind\": {\n" +
			"          \"type\": \"string\",\n" +
			"          \"minLength\": 1,\n" +
			"          \"description\": \"What sort of thing this is, so a consumer tells a missing tool from a tool that" +
			" found problems without reading English. The vocabulary is deliberately not enumerated here: a closed list w" +
			"ould make a schema change the price of a new kind of failure.\"\n" +
			"        }\n" +
			"      }\n" +
			"    }\n" +
			"  }\n" +
			"}\n",
	},
	{
		"jig.schema.json",
		"{\n" +
			"  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n" +
			"  \"$id\": \"https://scriptedworld.github.io/wrench/jig.schema.json\",\n" +
			"  \"title\": \"jig\",\n" +
			"  \"description\": \"A jig: the unit of configuration and composition. What a runner executes for a project " +
			"is read from that project's jig. Unrecognised keys are not refused here, because whether an unknown key fail" +
			"s or warns is still open, and a schema that leaves something open leaves it open.\",\n" +
			"\n" +
			"  \"type\": \"object\",\n" +
			"  \"required\": [\"tasks\"],\n" +
			"\n" +
			"  \"properties\": {\n" +
			"    \"version\": {\n" +
			"      \"type\": \"string\",\n" +
			"      \"pattern\": \"^(0|[1-9]\\\\d*)\\\\.(0|[1-9]\\\\d*)\\\\.(0|[1-9]\\\\d*)(?:-((?:0|[1-9]\\\\d*|\\\\d*[a-" +
			"zA-Z-][0-9a-zA-Z-]*)(?:\\\\.(?:0|[1-9]\\\\d*|\\\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\\+([0-9a-zA-Z-]+(?:\\\\" +
			".[0-9a-zA-Z-]+)*))?$\",\n" +
			"      \"description\": \"The version of this format the document claims to conform to, as semver. Optional, " +
			"and absent means the document claims nothing, which is every document written before this field existed. Pre" +
			"sent, it lets a consumer refuse a major it does not understand rather than failing later on a field it canno" +
			"t find.\"\n" +
			"    },\n" +
			"\n" +
			"    \"requires\": {\n" +
			"      \"type\": \"array\",\n" +
			"      \"description\": \"Every executable this jig invokes: the tools its commands run, the adapters its tas" +
			"ks name, any checker it calls. The whole dependency inventory, not a note about unusual tools.\",\n" +
			"      \"items\": { \"type\": \"string\", \"minLength\": 1 }\n" +
			"    },\n" +
			"\n" +
			"    \"definitions\": {\n" +
			"      \"$ref\": \"https://scriptedworld.github.io/wrench/definitions.schema.json\",\n" +
			"      \"description\": \"Default values for the placeholders this jig's commands name. Optional, and so is a" +
			"ny entry in it: a jig leaving a value to its adopter names the placeholder and defines nothing. A definition" +
			"s file named on the invocation merges over this.\"\n" +
			"    },\n" +
			"\n" +
			"    \"needs-repository-root\": {\n" +
			"      \"type\": \"boolean\",\n" +
			"      \"default\": false,\n" +
			"      \"description\": \"This jig's commands stand at the repository root rather than at their base. It reac" +
			"hes the working directory and nothing else: the walk, the containment, the filter patterns and {base_dir} al" +
			"l stay what the caller granted. A property of the tool the jig runs rather than of any one caller placing it" +
			", so it sits on the jig and not on the jig task.\"\n" +
			"    },\n" +
			"\n" +
			"    \"tasks\": {\n" +
			"      \"type\": \"array\",\n" +
			"      \"description\": \"Executed in declaration order. A task names either a command or a jig, never both." +
			"\",\n" +
			"      \"minItems\": 1,\n" +
			"      \"items\": { \"$ref\": \"#/$defs/task\" }\n" +
			"    }\n" +
			"  },\n" +
			"\n" +
			"  \"$defs\": {\n" +
			"    \"task\": {\n" +
			"      \"type\": \"object\",\n" +
			"      \"required\": [\"name\"],\n" +
			"\n" +
			"      \"properties\": {\n" +
			"        \"name\": {\n" +
			"          \"type\": \"string\",\n" +
			"          \"minLength\": 1,\n" +
			"          \"description\": \"Prefixes this task's work directories, so its evidence is identifiable on disk " +
			"without opening anything. Unique within the jig.\"\n" +
			"        },\n" +
			"        \"description\": { \"type\": \"string\" },\n" +
			"        \"short-circuit-failure\": {\n" +
			"          \"type\": \"boolean\",\n" +
			"          \"default\": false,\n" +
			"          \"description\": \"Stop the run when this task fails. Stopping is what a jig asks for rather than " +
			"what it gets.\"\n" +
			"        },\n" +
			"\n" +
			"        \"command\": {\n" +
			"          \"type\": \"string\",\n" +
			"          \"minLength\": 1,\n" +
			"          \"description\": \"A shell line. How it runs is read off it: {each_path} means one execution per m" +
			"atched path, {all_paths} one execution with the whole selection. Naming both is an error.\"\n" +
			"        },\n" +
			"        \"matching\": { \"$ref\": \"#/$defs/pathList\" },\n" +
			"        \"excluding\": { \"$ref\": \"#/$defs/pathList\" },\n" +
			"        \"allow-empty\": {\n" +
			"          \"type\": \"boolean\",\n" +
			"          \"default\": false,\n" +
			"          \"description\": \"An empty selection is an acceptable result for this task. Left out, a filtered " +
			"selection matching nothing is a failure, because a pattern that matches nothing is far more often a stale pa" +
			"th than a deliberate one. Only meaningful where a selection exists, so a command naming neither {each_path} " +
			"nor {all_paths} may not declare it.\"\n" +
			"        },\n" +
			"        \"adapter\": {\n" +
			"          \"type\": \"string\",\n" +
			"          \"minLength\": 1,\n" +
			"          \"description\": \"Resolved by name from the config directory. Left out, the generic exit-code ada" +
			"pter runs.\"\n" +
			"        },\n" +
			"        \"adapter-command\": {\n" +
			"          \"type\": \"string\",\n" +
			"          \"minLength\": 1,\n" +
			"          \"description\": \"An explicit adapter invocation, written in place of the default one. The same s" +
			"ubstitutions are available as in a command, and the envelope is still expected at output.yaml in the work di" +
			"rectory, because no flag says where it goes.\"\n" +
			"        },\n" +
			"        \"evidence\": {\n" +
			"          \"type\": \"array\",\n" +
			"          \"description\": \"The files this task produces that its adapter should read. Declared, never disc" +
			"overed.\",\n" +
			"          \"items\": { \"type\": \"string\", \"minLength\": 1 }\n" +
			"        },\n" +
			"\n" +
			"        \"jig\": {\n" +
			"          \"type\": \"string\",\n" +
			"          \"minLength\": 1,\n" +
			"          \"description\": \"Run this jig instead of a command. The child follows its own process: its own r" +
			"equires, its own tasks, its own filtering.\"\n" +
			"        },\n" +
			"        \"in\": {\n" +
			"          \"type\": \"string\",\n" +
			"          \"minLength\": 1,\n" +
			"          \"description\": \"A subdirectory of the current base to run the named jig in. A written path, not" +
			" a pattern, because a pattern can say which files look like Go and never that a directory is a Go module. Th" +
			"e only thing that sets a child's base.\"\n" +
			"        },\n" +
			"        \"config-dir\": {\n" +
			"          \"type\": \"string\",\n" +
			"          \"minLength\": 1,\n" +
			"          \"description\": \"Where the child looks for jigs. Left out, it inherits.\"\n" +
			"        },\n" +
			"        \"output-dir\": {\n" +
			"          \"type\": \"string\",\n" +
			"          \"minLength\": 1,\n" +
			"          \"description\": \"Names the child's output directory rather than placing it. Whatever it is set t" +
			"o, the result is a subdirectory of this task's work directory.\"\n" +
			"        },\n" +
			"        \"definitions\": {\n" +
			"          \"type\": \"string\",\n" +
			"          \"minLength\": 1,\n" +
			"          \"description\": \"Names the child's definitions file, as --definitions does for an invocation fro" +
			"m the command line. Left out, it inherits, so subprojects sharing one set of adjustments name nothing and ca" +
			"rry no copies.\"\n" +
			"        }\n" +
			"      },\n" +
			"\n" +
			"      \"oneOf\": [\n" +
			"        {\n" +
			"          \"title\": \"a command task\",\n" +
			"          \"required\": [\"command\"],\n" +
			"          \"properties\": {\n" +
			"            \"jig\": false,\n" +
			"            \"in\": false,\n" +
			"            \"config-dir\": false,\n" +
			"            \"output-dir\": false,\n" +
			"            \"definitions\": false,\n" +
			"            \"needs-repository-root\": false\n" +
			"          },\n" +
			"          \"if\": {\n" +
			"            \"required\": [\"allow-empty\"],\n" +
			"            \"properties\": { \"allow-empty\": { \"const\": true } }\n" +
			"          },\n" +
			"          \"then\": {\n" +
			"            \"properties\": {\n" +
			"              \"command\": {\n" +
			"                \"pattern\": \"\\\\{each_path\\\\}|\\\\{all_paths\\\\}\",\n" +
			"                \"$comment\": \"allow-empty says an empty SELECTION is acceptable, so a command with no sele" +
			"ction to be empty cannot declare it. Refused here rather than left to the runner, because it is a property o" +
			"f the jig as written.\"\n" +
			"              }\n" +
			"            }\n" +
			"          }\n" +
			"        },\n" +
			"        {\n" +
			"          \"title\": \"a jig task\",\n" +
			"          \"required\": [\"jig\"],\n" +
			"          \"properties\": {\n" +
			"            \"command\": false,\n" +
			"            \"adapter\": false,\n" +
			"            \"adapter-command\": false,\n" +
			"            \"evidence\": false,\n" +
			"            \"matching\": false,\n" +
			"            \"excluding\": false,\n" +
			"            \"allow-empty\": false,\n" +
			"            \"needs-repository-root\": false\n" +
			"          }\n" +
			"        }\n" +
			"      ]\n" +
			"    },\n" +
			"\n" +
			"    \"pathList\": {\n" +
			"      \"type\": \"array\",\n" +
			"      \"description\": \"Patterns or literal paths, relative to the base of the run they are declared in, wh" +
			"ere ** matches zero or more directory levels.\",\n" +
			"      \"items\": { \"type\": \"string\", \"minLength\": 1 }\n" +
			"    }\n" +
			"  }\n" +
			"}\n",
	},
	{
		"manifest.schema.json",
		"{\n" +
			"  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n" +
			"  \"$id\": \"https://scriptedworld.github.io/wrench/manifest.schema.json\",\n" +
			"  \"title\": \"manifest\",\n" +
			"  \"description\": \"What one task execution was going to be given, written before its command runs. It ther" +
			"efore holds only what is known beforehand: anything a run learns by finishing is not in here, because the ma" +
			"nifest was closed before there was anything to learn.\",\n" +
			"\n" +
			"  \"type\": \"object\",\n" +
			"  \"required\": [\"task\", \"ordinal\", \"command\", \"variables\"],\n" +
			"\n" +
			"  \"properties\": {\n" +
			"    \"version\": {\n" +
			"      \"type\": \"string\",\n" +
			"      \"pattern\": \"^(0|[1-9]\\\\d*)\\\\.(0|[1-9]\\\\d*)\\\\.(0|[1-9]\\\\d*)(?:-((?:0|[1-9]\\\\d*|\\\\d*[a-" +
			"zA-Z-][0-9a-zA-Z-]*)(?:\\\\.(?:0|[1-9]\\\\d*|\\\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\\+([0-9a-zA-Z-]+(?:\\\\" +
			".[0-9a-zA-Z-]+)*))?$\",\n" +
			"      \"description\": \"The version of this format the document claims to conform to, as semver. Optional, " +
			"and absent means the document claims nothing, which is every document written before this field existed. Pre" +
			"sent, it lets a consumer refuse a major it does not understand rather than failing later on a field it canno" +
			"t find.\"\n" +
			"    },\n" +
			"\n" +
			"    \"task\": {\n" +
			"      \"type\": \"string\",\n" +
			"      \"minLength\": 1,\n" +
			"      \"description\": \"The task this execution belongs to.\"\n" +
			"    },\n" +
			"    \"ordinal\": {\n" +
			"      \"type\": \"integer\",\n" +
			"      \"minimum\": 0,\n" +
			"      \"description\": \"This execution's index within the task.\"\n" +
			"    },\n" +
			"    \"command\": {\n" +
			"      \"type\": \"string\",\n" +
			"      \"description\": \"The command line as executed, after substitution.\"\n" +
			"    },\n" +
			"    \"variables\": {\n" +
			"      \"type\": \"object\",\n" +
			"      \"description\": \"Every value exposed as a template variable for this execution, whether or not the c" +
			"ommand used it, with the layer each came from. A reader sees what the task was given and not only what its c" +
			"ommand became, which matters where a variable was available and went unused, and where a definition overrode" +
			" what the jig shipped.\",\n" +
			"      \"propertyNames\": {\n" +
			"        \"pattern\": \"^[a-z][a-z0-9_]*$\"\n" +
			"      },\n" +
			"      \"additionalProperties\": {\n" +
			"        \"type\": \"object\",\n" +
			"        \"required\": [\"value\", \"from\"],\n" +
			"        \"properties\": {\n" +
			"          \"value\": {\n" +
			"            \"type\": [\"string\", \"array\"],\n" +
			"            \"items\": { \"type\": \"string\" },\n" +
			"            \"description\": \"What the placeholder stood for. A list only where the variable is itself a li" +
			"st of paths.\"\n" +
			"          },\n" +
			"          \"from\": {\n" +
			"            \"enum\": [\"bolt\", \"jig\", \"file\"],\n" +
			"            \"description\": \"Which layer supplied it: a location or path variable bolt reserves, the jig's" +
			" own definitions block, or the definitions file named on the invocation. The same key means different things" +
			" depending on which won, and the command line alone does not say.\"\n" +
			"          }\n" +
			"        }\n" +
			"      },\n" +
			"      \"required\": [\n" +
			"        \"project_root\",\n" +
			"        \"base_dir\",\n" +
			"        \"work_dir\",\n" +
			"        \"config_dir\",\n" +
			"        \"output_dir\"\n" +
			"      ]\n" +
			"    },\n" +
			"    \"selection\": {\n" +
			"      \"type\": \"object\",\n" +
			"      \"description\": \"What the task was offered and what it was kept from seeing. Present for a task that" +
			" consumes paths.\",\n" +
			"      \"properties\": {\n" +
			"        \"matched\": {\n" +
			"          \"type\": \"array\",\n" +
			"          \"items\": { \"type\": \"string\" },\n" +
			"          \"description\": \"The whole matched list, repeated in every execution of a per-path task, because" +
			" one path alone loses the context of what the task was offered.\"\n" +
			"        },\n" +
			"        \"excluded\": {\n" +
			"          \"type\": \"array\",\n" +
			"          \"items\": { \"type\": \"string\" }\n" +
			"        }\n" +
			"      }\n" +
			"    }\n" +
			"  }\n" +
			"}\n",
	},
}
