//! Reads `schemas/` and generates the embedding for it.
//!
//! FR-3.7 says a pack discovers the shipped schemas by reading the directory
//! they live in, not from a list of filenames in its own source. FR-3.5 says a
//! pack may embed them to link a single static binary, which is what bolt wants.
//!
//! Rust has no directory embed in the standard library and `include_str!` needs
//! a literal path, so the directory is read HERE, at build time, and the list is
//! generated. Adding a fifth schema needs no edit to any source file, and the
//! binary still carries them.
//!
//! A build script rather than the `include_dir` crate: this is a dozen lines and
//! costs no dependency, and a pack whose whole argument is binding rather than
//! implementing should not take one for a directory listing.

use std::{env, fs, path::PathBuf};

fn main() {
    // ../schemas, the one copy every pack reads. Not a copy under rust/.
    let schemas = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("rust/ has a parent")
        .join("schemas");

    println!("cargo:rerun-if-changed={}", schemas.display());

    let mut entries: Vec<PathBuf> = fs::read_dir(&schemas)
        .unwrap_or_else(|e| panic!("reading {}: {e}", schemas.display()))
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|path| path.to_string_lossy().ends_with(".schema.json"))
        .collect();
    entries.sort();

    assert!(
        !entries.is_empty(),
        "{} holds no schemas, so the pack would ship none",
        schemas.display()
    );

    let mut generated = String::from(
        "// Generated by build.rs from the schemas directory. Do not edit.\n\
         pub(crate) const SHIPPED: &[(&str, &str)] = &[\n",
    );
    for path in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
        let name = path.file_name().expect("a file").to_string_lossy();
        generated.push_str(&format!(
            "    ({name:?}, include_str!({:?})),\n",
            path.to_string_lossy()
        ));
    }
    generated.push_str("];\n");

    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("shipped.rs");
    fs::write(&out, generated).unwrap_or_else(|e| panic!("writing {}: {e}", out.display()));
}
